services:
  api:
    build:
      context: .
      dockerfile: UnivAuth.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__dbPersona=Host=${POSTGRES_IP_SERVER};Port=5432;Database=${POSTGRES_BD_NAME};Username=postgres;Password=${POSTGRES_ROOT_PASSWORD};